---
title: "Shape Files"
output: html_notebook
---

```{r results = FALSE, include = FALSE}
library(sf)
library(sp)
library(tidyverse)
```

```{r results = FALSE, include = FALSE}
# read data
aff <-
  st_read("satSCANoutputs/aff.col.shp")
alc <-
  st_read("satSCANoutputs/alc.col.shp")
anx <-
  st_read("satSCANoutputs/anx.col.shp")
any <-
  st_read("satSCANoutputs/any.col.shp")
ukroblast <-
  st_read("ukraineGIS/gadm36_UKR_1.shp")
```

```{r}
# adjust ukroblast
ukroblast1 <-
  ukroblast %>%
  mutate(LOC_ID = as.factor(str_replace_all(NAME_1, "[^[:alnum:]]", "")))
```

```{r}
# anxiety map
anx_ind <-
  anx %>%
  mutate(Risk = ifelse(REL_RISK > 1, "High", "Low")) %>%
  filter(GINI_CLUST == 'T')

ukroblast_anx_map <-
  ukroblast %>%
  st_join(anx_ind, by = "LOC_ID") %>%
  filter(!((NAME_1 == "Zhytomyr") & (Risk == "Low"))) %>%
  mutate(Risk = ifelse(Risk %in% c('High', 'Low'), Risk, 'Expected'))

ggplot(data = ukroblast_anx_map, aes(fill = Risk)) +
  geom_sf() +
  labs(title = "Anxiety Disorder Clusters") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank()) +
  scale_fill_manual(values = c("#999999", "#E69F00", "#56B4E9")) 

ggsave('ClusterImages/anxiety.png')
```

```{r}
# affective map
aff_ind <-
  aff %>%
  mutate(Risk = ifelse(REL_RISK > 1, "High", "Low")) %>%
  filter(GINI_CLUST == 'T')

ukroblast_aff_map <-
  ukroblast %>%
  st_join(aff_ind, by = "LOC_ID") %>%
  #filter(!((NAME_1 == "Zhytomyr") & (Risk == "Low"))) %>%
  mutate(Risk = ifelse(Risk %in% c('High', 'Low'), Risk, 'Expected'))

ggplot(data = ukroblast_aff_map, aes(fill = Risk)) +
  geom_sf() +
  labs(title = "Affective Disorder Clusters") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank()) +
  scale_fill_manual(values = c("#999999", "#E69F00", "#56B4E9")) 

ggsave('ClusterImages/affective.png')
```

```{r}
# alcohol map
alc_ind <-
  alc %>%
  mutate(Risk = ifelse(REL_RISK > 1, "High", "Low")) %>%
  filter(GINI_CLUST == 'T')

ukroblast_alc_map <-
  ukroblast %>%
  st_join(alc_ind, by = "LOC_ID") %>%
  #filter(!((NAME_1 == "Zhytomyr") & (Risk == "Low"))) %>%
  mutate(Risk = ifelse(Risk %in% c('High', 'Low'), Risk, 'Expected'))

ggplot(data = ukroblast_alc_map, aes(fill = Risk)) +
  geom_sf() +
  labs(title = "Alcohol Disorder Clusters") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank()) +
  scale_fill_manual(values = c("#999999", "#E69F00", "#56B4E9")) 

ggsave('ClusterImages/alcohol.png')
```

```{r}
# any map
any_ind <-
  any %>%
  mutate(Risk = ifelse(REL_RISK > 1, "High", "Low")) %>%
  filter(GINI_CLUST == 'T')

ukroblast_any_map <-
  ukroblast %>%
  st_join(any_ind, by = "LOC_ID") %>%
  #filter(!((NAME_1 == "Zhytomyr") & (Risk == "Low"))) %>%
  mutate(Risk = ifelse(Risk %in% c('High', 'Low'), Risk, 'Expected'))

ggplot(data = ukroblast_any_map, aes(fill = Risk)) +
  geom_sf() +
  labs(title = "Any Disorder Clusters") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank()) +
  scale_fill_manual(values = c("#999999", "#E69F00", "#56B4E9")) 

ggsave('ClusterImages/any.png')
```

```{r}
# ggplot(data = ukroblast) +
#   geom_sf() + 
#   geom_sf(data = ied, aes(alpha = 0.00000001)) +
#   labs(title = "IED Clusters") +
#   theme(panel.grid.major = element_blank(), 
#         panel.grid.minor = element_blank(),
#         legend.position = "none")
# 
# ggplot(data = ukroblast) +
#   geom_sf() + 
#   geom_sf(data = aff_nocov, aes(alpha = 0.00000001)) +
#   labs(title = "Affective Disorders Clusters") +
#   theme(panel.grid.major = element_blank(), 
#         panel.grid.minor = element_blank(),
#         legend.position = "none")
# 
# ggplot(data = ukroblast) +
#   geom_sf() + 
#   geom_sf(data = alc_nocov, aes(alpha = 0.00000001)) +
#   labs(title = "Alcohol Disorder Clusters") +
#   theme(panel.grid.major = element_blank(), 
#         panel.grid.minor = element_blank(),
#         legend.position = "none")

# ggplot(data = ukroblast) +
#   geom_sf() + 
#   geom_sf(data = anx_ind, aes(alpha = 0.00000001)) +
#   labs(title = "Anxiety Disorders Clusters") +
#   theme(panel.grid.major = element_blank(), 
#         panel.grid.minor = element_blank(),
#         legend.position = "none")
```










