---
title: "Shiny App Analysis"
output: html_notebook
---

```{r include = FALSE}
# load libraries
library(tidyverse)
library(data.table)
library(SpatialEpiApp)
library(sf)
```

```{r}
# read data
case_raw <- fread("case_shiny.csv")
pop <- fread("population_sev.csv")
ukroblast <- st_read("ukraineGIS/gadm36_UKR_1.shp")
geo <- fread("satSCANinputs/coord_file.csv")
```

```{r}
# format data
case <-
  case_raw %>%
  left_join(pop) %>%
  mutate(date = 2004,
         NAME_1 = Oblast)

case1 <-
  case %>%
  select(NAME_1, Population, date, any)

geo1 <- rbind(geo, geo[rep(4, 1)])
geo1[27]$Oblast = "Sevastopol'"
geo_final <-
  geo1 %>%
  arrange(Oblast) %>%
  select(latitude, longitude)

# fwrite(case, "case_shiny_final.csv")
# fwrite(case1, "case_any.csv")
```

```{r}
# launch SpatialEpiApp
run_app()
```

```{r}
# Any Disorder
exp_any <- SpatialEpi::expected(case$Population, case$any, 1)
out_any <-
  SpatialEpi::kulldorff(geo_final, case$any, case$Population, exp_any, pop.upper.bound = 0.5, n.simulations = 999, alpha.level = .05, plot = FALSE)

any_most_cluster <- out_any$most.likely.cluster$location.IDs.included
any_second_cluster <- c(out_any$secondary.clusters[[1]]$location.IDs.included, 
                        out_any$secondary.clusters[[2]]$location.IDs.included,
                        out_any$secondary.clusters[[3]]$location.IDs.included)

ukroblast$anyrisk <- "Low"
ukroblast$anyrisk[any_most_cluster] <- "High"
ukroblast$anyrisk[any_second_cluster] <- "Medium"

ggplot(data = ukroblast, aes(fill = anyrisk)) +
  geom_sf() +
  labs(title = "Clusters, Any Mental Disorder",
       fill = "Risk Level") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
```

```{r}
# Anxiety Disorder
exp_anx <- SpatialEpi::expected(case$Population, case$anx, 1)
out_anx <-
  SpatialEpi::kulldorff(geo_final, case$anx, case$Population, exp_anx, pop.upper.bound = 0.5, n.simulations = 999, alpha.level = .05, plot = FALSE)

anx_most_cluster <- out_anx$most.likely.cluster$location.IDs.included
anx_second_cluster <- c(out_anx$secondary.clusters[[1]]$location.IDs.included, 
                        out_anx$secondary.clusters[[2]]$location.IDs.included)

ukroblast$anxrisk <- "No Cluster Detected"
ukroblast$anxrisk[anx_most_cluster] <- "Most Likely Cluster"
ukroblast$anxrisk[anx_second_cluster] <- "Secondary Cluster"

anx_plot <- ggplot(data = ukroblast, aes(fill = anxrisk)) +
  geom_sf() +
  labs(title = "Oblasts with Higher Prevalence Rates of Anxiety Disorders",
       fill = "Legend", 
       x= 'x',
       y = 'y') +
  geom_text(aes(x=coords$longitude, y=coords$latitude, label=coords$Oblast),
       color = "black",size = 2, fontface = "bold", check_overlap = FALSE) 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
  
  
ggsave("anx_cluster_mapping.png",
       plot = anx_plot)
```

```{r}
# IED Disorders
exp_ied <- SpatialEpi::expected(case$Population, case$ied, 1)
out_ied <-
  SpatialEpi::kulldorff(geo_final, case$ied, case$Population, exp_ied, pop.upper.bound = 0.5, n.simulations = 999, alpha.level = .05, plot = FALSE)

ied_most_cluster <- out_ied$most.likely.cluster$location.IDs.included
# ied_second_cluster <- c(out_ied$secondary.clusters[[1]]$location.IDs.included, 
#                         out_ied$secondary.clusters[[2]]$location.IDs.included,
#                         out_ied$secondary.clusters[[3]]$location.IDs.included)
# were there no secondary clusters? why is this comented out?

ukroblast$iedrisk <- "No Clusters Detected"
ukroblast$iedrisk[ied_most_cluster] <- "Most Likely Cluster"
# ukroblast$iedrisk[any_second_cluster] <- "Medium"

iedplot <- ggplot(data = ukroblast, aes(fill = iedrisk)) +
  geom_sf() +
  labs(title = "Oblasts with Higher Prevalence of IED",
       fill = "Legend",
       x = 'x',
       y = 'y') +
  geom_text(aes(x=coords$longitude, y=coords$latitude, label=coords$Oblast),
       color = "black",size = 2, fontface = "bold", check_overlap = FALSE) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())

ggsave('ied_cluster_mapping.png',
       plot = iedplot)
```

```{r}
# Affective Disorders
exp_aff <- SpatialEpi::expected(case$Population, case$aff, 1)
out_aff <-
  SpatialEpi::kulldorff(geo_final, case$aff, case$Population, exp_aff, pop.upper.bound = 0.5, n.simulations = 999, alpha.level = .05, plot = FALSE)

aff_most_cluster <- out_aff$most.likely.cluster$location.IDs.included
aff_second_cluster <- c(out_aff$secondary.clusters[[1]]$location.IDs.included,
                        out_aff$secondary.clusters[[2]]$location.IDs.included,
                        out_aff$secondary.clusters[[3]]$location.IDs.included)

ukroblast$affrisk <- "No Clusters Detected"
ukroblast$affrisk[aff_most_cluster] <- "Most Likely Cluster"
ukroblast$affrisk[aff_second_cluster] <- "Secondary Cluster"

affplot <- ggplot(data = ukroblast, aes(fill = affrisk)) +
  geom_sf() +
  labs(title = "Oblasts with Higher Prevalence of Affective Disorders",
       fill = "Legend",
       x = 'x',
       y = 'y') +
  geom_text(aes(x=coords$longitude, y=coords$latitude, label=coords$Oblast),
       color = "black",size = 2, fontface = "bold", check_overlap = FALSE) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())

ggsave('aff_cluster_mapping.png',
       plot = affplot)
```

```{r}
# Alcohol Disorders
exp_alc <- SpatialEpi::expected(case$Population, case$alc, 1)
out_alc <-
  SpatialEpi::kulldorff(geo_final, case$alc, case$Population, exp_alc, pop.upper.bound = 0.5, n.simulations = 999, alpha.level = .05, plot = FALSE)

alc_most_cluster <- out_alc$most.likely.cluster$location.IDs.included
# alc_second_cluster <- c(out_alc$secondary.clusters[[1]]$location.IDs.included,
#                         out_alc$secondary.clusters[[2]]$location.IDs.included,
#                         out_alc$secondary.clusters[[3]]$location.IDs.included)

ukroblast$alcrisk <- "No Clusters Detected"
ukroblast$alcrisk[alc_most_cluster] <- "Most Likely Cluster"
# ukroblast$affrisk[aff_second_cluster] <- "Medium"

alcplot <- ggplot(data = ukroblast, aes(fill = alcrisk)) +
  geom_sf() +
  labs(title = "Oblasts with Higher Prevalence of Alcohol Disorders",
       fill = "Legend",
       x = 'x',
       y = 'y') +
  geom_text(aes(x=coords$longitude, y=coords$latitude, label=coords$Oblast),
       color = "black",size = 2, fontface = "bold", check_overlap = FALSE) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())

ggsave('alc_cluster_mapping.png',
       plot = alcplot)
```

